server:
  port: 9001

spring:
  application:
    name: users-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    password: admin1234
#    url: jdbc:mysql://localhost:3306/userservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://mysql:3306/userservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  #zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    # baseUrl: https://192.168.99.100:9411/

  # Trace all request on ZipKin
  sleuth:
    sampler:
      probability: 1.0
      # Trace 10% of request on Zipkin
      #probability: 0.1

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka