server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8888
    #import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  # Sample all request on ZipKin
  sleuth:
    sampler:
      probability: 1.0
      # Trace 10% of request on Zipkin
      #probability: 0.1

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka