server:
  port: 9003

spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    password: secret
    url: jdbc:mysql://localhost:3306/bookingservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  # Sample all request on ZipKin
  sleuth:
    sampler:
      probability: 1.0
      # Trace 10% of request on Zipkin
      #probability: 0.1

resilience4j.circuitbreaker:
  instances:
    hotel-service:
      automatic-transition-from-open-to-half-open-enabled: true
      failure-rate-threshold: 80
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 4
      sliding-window-size: 10
      sliding-window-type: COUNT_BASED
      wait-duration-in-open-state: 10s


resilience4j.retry:
  instances:
    hotel-service:
      maxAttempts: 5
      waitDuration: 2s
      enableExponentialBackoff: true
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException



