apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-app
  labels:
    app: booking-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service-app
  template:
    metadata:
      labels:
        app: booking-service-app
    spec:
      containers:
      - name: booking-service-app
        image: epaitoo/hotel-microservice-booking-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/bookingservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.MySQL5InnoDBDialect
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: update
        - name: SPRING_CONFIG_IMPORT 
          value: optional:configserver:http://config-server:8888
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: eureka-0
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
        - name: SPRING_ZIPKIN_BASEURL
          value: http://zipkin-server:9411/
        - name: RABBIT_URI
          value: amqp://guest:guest@rabbitmq:5672
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_ZIPKIN_SENDER_TYPE
          value: rabbit
---

kind: Service
apiVersion: v1
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service-app
  ports:
  - port: 80
    targetPort: 9003

