# RABBITMQ DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.5.5-management
        ports:
        - containerPort: 5672

---
# RABBITMQ SERVICE

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 80
    targetPort: 5672

---


# ZIPKIN SERVER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: openzipkin/zipkin:2.23
        ports:
        - containerPort: 9411
        env:
          - name: RABBIT_URI
            value: amqp://guest:guest@rabbitmq:5672

---

# ZIPKIN-SERVER SERVICE
kind: Service
apiVersion: v1
metadata:
  name: zipkin-server
spec:
  type: LoadBalancer
  selector:
    app: zipkin-server
  ports:
  - port: 80
    targetPort: 9411
    protocol: TCP
