apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service-app
  labels:
    app: hotel-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service-app
  template:
    metadata:
      labels:
        app: hotel-service-app
    spec:
      containers:
      - name: hotel-service-app
        image: epaitoo/hotel-microservice-hotel-service:0.0.2-RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/hotelservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.MySQL5InnoDBDialect
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: update
        - name: SPRING_CONFIG_IMPORT 
          value: optional:configserver:http://config-server:8888
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: eureka-0
        - name: EUREKA_CLIENT_REGISTERWITHEUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCHREGISTRY
          value: "true"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---

kind: Service
apiVersion: v1
metadata:
  name:  hotel-service
spec:
  selector:
    app:  hotel-service-app
  ports:
  - port: 80
    targetPort: 9002

